ALTER TABLE products
  ADD COLUMN peso DECIMAL(10,2) NULL AFTER stock,
  ADD COLUMN alto DECIMAL(10,2) NULL AFTER peso,
  ADD COLUMN ancho DECIMAL(10,2) NULL AFTER alto,
  ADD COLUMN largo DECIMAL(10,2) NULL AFTER ancho;
